from __future__ import annotations

"""Derived ASME B36.10-compatible pipe size catalog for UI selection.

Source used to derive this embedded table:
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-a.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-b.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-c.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-d.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-e.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-f.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-g.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-h.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-i.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-j.html
- https://www.wermac.org/pipes/dim_b36.10_pipes_part-k.html

This table covers NPS 1/8 through NPS 80. It is provided for software
convenience and should still be validated against the licensed ASME
B36.10/B36.10M standard or company procedure before field use.
"""

PIPE_CATALOG = [{'nps': '1/8',
  'dn': '6',
  'outside_diameter_mm': 10.3,
  'schedules': [{'label': '10', 'wall_thickness_mm': 1.24},
                {'label': '30', 'wall_thickness_mm': 1.45},
                {'label': '40 / STD', 'wall_thickness_mm': 1.73},
                {'label': '80 / XS', 'wall_thickness_mm': 2.41},
                {'label': '160', 'wall_thickness_mm': 3.15},
                {'label': 'XXS', 'wall_thickness_mm': 4.83}]},
 {'nps': '1/4',
  'dn': '8',
  'outside_diameter_mm': 13.7,
  'schedules': [{'label': '10', 'wall_thickness_mm': 1.65},
                {'label': '30', 'wall_thickness_mm': 1.85},
                {'label': '40 / STD', 'wall_thickness_mm': 2.24},
                {'label': '80 / XS', 'wall_thickness_mm': 3.02},
                {'label': '160', 'wall_thickness_mm': 3.68},
                {'label': 'XXS', 'wall_thickness_mm': 6.05}]},
 {'nps': '3/8',
  'dn': '10',
  'outside_diameter_mm': 17.1,
  'schedules': [{'label': '10', 'wall_thickness_mm': 1.65},
                {'label': '30', 'wall_thickness_mm': 1.85},
                {'label': '40 / STD', 'wall_thickness_mm': 2.31},
                {'label': '80 / XS', 'wall_thickness_mm': 3.2},
                {'label': '160', 'wall_thickness_mm': 4.01},
                {'label': 'XXS', 'wall_thickness_mm': 6.4}]},
 {'nps': '1/2',
  'dn': '15',
  'outside_diameter_mm': 21.3,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '10', 'wall_thickness_mm': 2.11},
                {'label': '30', 'wall_thickness_mm': 2.41},
                {'label': '40 / STD', 'wall_thickness_mm': 2.77},
                {'label': '80 / XS', 'wall_thickness_mm': 3.73},
                {'label': '160', 'wall_thickness_mm': 4.78},
                {'label': 'XXS', 'wall_thickness_mm': 7.47}]},
 {'nps': '3/4',
  'dn': '20',
  'outside_diameter_mm': 26.7,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '10', 'wall_thickness_mm': 2.11},
                {'label': '30', 'wall_thickness_mm': 2.41},
                {'label': '40 / STD', 'wall_thickness_mm': 2.87},
                {'label': '80 / XS', 'wall_thickness_mm': 3.91},
                {'label': '160', 'wall_thickness_mm': 5.56},
                {'label': 'XXS', 'wall_thickness_mm': 7.82}]},
 {'nps': '1',
  'dn': '25',
  'outside_diameter_mm': 33.4,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '10', 'wall_thickness_mm': 2.77},
                {'label': '30', 'wall_thickness_mm': 2.9},
                {'label': '40 / STD', 'wall_thickness_mm': 3.38},
                {'label': '80 / XS', 'wall_thickness_mm': 4.55},
                {'label': '160', 'wall_thickness_mm': 6.35},
                {'label': 'XXS', 'wall_thickness_mm': 9.09}]},
 {'nps': '1 1/4',
  'dn': '32',
  'outside_diameter_mm': 42.2,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '10', 'wall_thickness_mm': 2.77},
                {'label': '30', 'wall_thickness_mm': 2.97},
                {'label': '40 / STD', 'wall_thickness_mm': 3.56},
                {'label': '80 / XS', 'wall_thickness_mm': 4.85},
                {'label': '160', 'wall_thickness_mm': 6.35},
                {'label': 'XXS', 'wall_thickness_mm': 9.7}]},
 {'nps': '1 1/2',
  'dn': '40',
  'outside_diameter_mm': 48.3,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '10', 'wall_thickness_mm': 2.77},
                {'label': '30', 'wall_thickness_mm': 3.18},
                {'label': '40 / STD', 'wall_thickness_mm': 3.68},
                {'label': '80 / XS', 'wall_thickness_mm': 5.08},
                {'label': '160', 'wall_thickness_mm': 7.14},
                {'label': 'XXS', 'wall_thickness_mm': 10.15}]},
 {'nps': '2',
  'dn': '50',
  'outside_diameter_mm': 60.3,
  'schedules': [{'label': '5', 'wall_thickness_mm': 1.65},
                {'label': '', 'wall_thickness_mm': 2.11},
                {'label': '10', 'wall_thickness_mm': 2.77},
                {'label': '30', 'wall_thickness_mm': 3.18},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '40 / STD', 'wall_thickness_mm': 3.91},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '80 / XS', 'wall_thickness_mm': 5.54},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '160', 'wall_thickness_mm': 8.74},
                {'label': 'XXS', 'wall_thickness_mm': 11.07}]},
 {'nps': '2 1/2',
  'dn': '65',
  'outside_diameter_mm': 73.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 2.11},
                {'label': '', 'wall_thickness_mm': 2.77},
                {'label': '10', 'wall_thickness_mm': 3.05},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '30', 'wall_thickness_mm': 4.78},
                {'label': '40 / STD', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.49},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '80 / XS', 'wall_thickness_mm': 7.01},
                {'label': '160', 'wall_thickness_mm': 9.53},
                {'label': 'XXS', 'wall_thickness_mm': 14.02}]},
 {'nps': '3',
  'dn': '80',
  'outside_diameter_mm': 88.9,
  'schedules': [{'label': '5', 'wall_thickness_mm': 2.11},
                {'label': '', 'wall_thickness_mm': 2.77},
                {'label': '10', 'wall_thickness_mm': 3.05},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '30', 'wall_thickness_mm': 4.78},
                {'label': '40 / STD', 'wall_thickness_mm': 5.49},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '80 / XS', 'wall_thickness_mm': 7.62},
                {'label': '160', 'wall_thickness_mm': 11.13},
                {'label': 'XXS', 'wall_thickness_mm': 15.24}]},
 {'nps': '3 1/2',
  'dn': '90',
  'outside_diameter_mm': 101.6,
  'schedules': [{'label': '5', 'wall_thickness_mm': 2.11},
                {'label': '', 'wall_thickness_mm': 2.77},
                {'label': '10', 'wall_thickness_mm': 3.05},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '30', 'wall_thickness_mm': 4.78},
                {'label': '40 / STD', 'wall_thickness_mm': 5.74},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '80 / XS', 'wall_thickness_mm': 8.08}]},
 {'nps': '4',
  'dn': '100',
  'outside_diameter_mm': 114.3,
  'schedules': [{'label': '5', 'wall_thickness_mm': 2.11},
                {'label': '', 'wall_thickness_mm': 2.77},
                {'label': '10', 'wall_thickness_mm': 3.05},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '30', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '40 / STD', 'wall_thickness_mm': 6.02},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '80 / XS', 'wall_thickness_mm': 8.56},
                {'label': '120', 'wall_thickness_mm': 11.13},
                {'label': '160', 'wall_thickness_mm': 13.49},
                {'label': 'XXS', 'wall_thickness_mm': 17.12}]},
 {'nps': '5',
  'dn': '125',
  'outside_diameter_mm': 141.3,
  'schedules': [{'label': '', 'wall_thickness_mm': 2.11},
                {'label': '5', 'wall_thickness_mm': 2.77},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '10', 'wall_thickness_mm': 3.4},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '40 / STD', 'wall_thickness_mm': 6.55},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '80 / XS', 'wall_thickness_mm': 9.53},
                {'label': '120', 'wall_thickness_mm': 12.7},
                {'label': '160', 'wall_thickness_mm': 15.88},
                {'label': 'XXS', 'wall_thickness_mm': 19.05}]},
 {'nps': '6',
  'dn': '150',
  'outside_diameter_mm': 168.3,
  'schedules': [{'label': '', 'wall_thickness_mm': 2.11},
                {'label': '5', 'wall_thickness_mm': 2.77},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '10', 'wall_thickness_mm': 3.4},
                {'label': '', 'wall_thickness_mm': 3.58},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '', 'wall_thickness_mm': 6.35},
                {'label': '40 / STD', 'wall_thickness_mm': 7.11},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '', 'wall_thickness_mm': 9.53},
                {'label': '80 / XS', 'wall_thickness_mm': 10.97},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '120', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '160', 'wall_thickness_mm': 18.26},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': 'XXS', 'wall_thickness_mm': 21.95},
                {'label': '', 'wall_thickness_mm': 22.23}]},
 {'nps': '8',
  'dn': '200',
  'outside_diameter_mm': 219.1,
  'schedules': [{'label': '5', 'wall_thickness_mm': 2.77},
                {'label': '', 'wall_thickness_mm': 3.18},
                {'label': '10', 'wall_thickness_mm': 3.76},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '20', 'wall_thickness_mm': 6.35},
                {'label': '30', 'wall_thickness_mm': 7.04},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '40 / STD', 'wall_thickness_mm': 8.18},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '', 'wall_thickness_mm': 9.53},
                {'label': '60', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '80 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '100', 'wall_thickness_mm': 15.09},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '120', 'wall_thickness_mm': 18.26},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '140', 'wall_thickness_mm': 20.62},
                {'label': 'XXS', 'wall_thickness_mm': 22.23},
                {'label': '160', 'wall_thickness_mm': 23.01},
                {'label': '', 'wall_thickness_mm': 25.4}]},
 {'nps': '10',
  'dn': '250',
  'outside_diameter_mm': 273.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 3.4},
                {'label': '', 'wall_thickness_mm': 3.96},
                {'label': '10', 'wall_thickness_mm': 4.19},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '20', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.09},
                {'label': '30', 'wall_thickness_mm': 7.8},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '40 / STD', 'wall_thickness_mm': 9.27},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '60 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '80', 'wall_thickness_mm': 15.09},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '100', 'wall_thickness_mm': 18.26},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '120', 'wall_thickness_mm': 21.44},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '140 / XXS', 'wall_thickness_mm': 25.4},
                {'label': '160', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '12',
  'dn': '300',
  'outside_diameter_mm': 323.8,
  'schedules': [{'label': '5', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.37},
                {'label': '10', 'wall_thickness_mm': 4.57},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '20', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '30', 'wall_thickness_mm': 8.38},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '40', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '60', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '80', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '100', 'wall_thickness_mm': 21.44},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '120 / XXS', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '140', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '160', 'wall_thickness_mm': 33.32}]},
 {'nps': '14',
  'dn': '350',
  'outside_diameter_mm': 355.6,
  'schedules': [{'label': '5', 'wall_thickness_mm': 3.96},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.33},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '20', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '30 / STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '40', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '60', 'wall_thickness_mm': 15.09},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '80', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '100', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '120', 'wall_thickness_mm': 27.79},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '140', 'wall_thickness_mm': 31.75},
                {'label': '160', 'wall_thickness_mm': 35.71},
                {'label': '', 'wall_thickness_mm': 50.8},
                {'label': '', 'wall_thickness_mm': 53.98},
                {'label': '', 'wall_thickness_mm': 55.88},
                {'label': '', 'wall_thickness_mm': 63.5}]},
 {'nps': '16',
  'dn': '400',
  'outside_diameter_mm': 406.4,
  'schedules': [{'label': '5', 'wall_thickness_mm': 4.19},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.16},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '20', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '30 / STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '40 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '60', 'wall_thickness_mm': 16.66},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '80', 'wall_thickness_mm': 21.44},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '100', 'wall_thickness_mm': 26.19},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '120', 'wall_thickness_mm': 30.96},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '140', 'wall_thickness_mm': 36.53},
                {'label': '160', 'wall_thickness_mm': 40.49}]},
 {'nps': '18',
  'dn': '450',
  'outside_diameter_mm': 457.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 4.19},
                {'label': '', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '20', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '30', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '40', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '60', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '80', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '100', 'wall_thickness_mm': 29.36},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '120', 'wall_thickness_mm': 34.93},
                {'label': '140', 'wall_thickness_mm': 39.67},
                {'label': '160', 'wall_thickness_mm': 45.24}]},
 {'nps': '20',
  'dn': '500',
  'outside_diameter_mm': 508.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '20 / STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '30 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '40', 'wall_thickness_mm': 15.09},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '60', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '80', 'wall_thickness_mm': 26.19},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '100', 'wall_thickness_mm': 32.54},
                {'label': '', 'wall_thickness_mm': 33.32},
                {'label': '', 'wall_thickness_mm': 34.93},
                {'label': '120', 'wall_thickness_mm': 38.1},
                {'label': '140', 'wall_thickness_mm': 44.45},
                {'label': '160', 'wall_thickness_mm': 50.01}]},
 {'nps': '22',
  'dn': '550',
  'outside_diameter_mm': 559.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 4.78},
                {'label': '', 'wall_thickness_mm': 5.56},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '20 / STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '30 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '60', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '80', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 33.32},
                {'label': '100', 'wall_thickness_mm': 34.93},
                {'label': '', 'wall_thickness_mm': 36.53},
                {'label': '', 'wall_thickness_mm': 38.1},
                {'label': '120', 'wall_thickness_mm': 41.28},
                {'label': '140', 'wall_thickness_mm': 47.63},
                {'label': '160', 'wall_thickness_mm': 53.98}]},
 {'nps': '24',
  'dn': '600',
  'outside_diameter_mm': 610.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 5.54},
                {'label': '10', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': '20 / STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '30', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '40', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '60', 'wall_thickness_mm': 24.61},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '80', 'wall_thickness_mm': 30.96},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 33.32},
                {'label': '', 'wall_thickness_mm': 34.93},
                {'label': '', 'wall_thickness_mm': 36.53},
                {'label': '', 'wall_thickness_mm': 38.1},
                {'label': '100', 'wall_thickness_mm': 38.89},
                {'label': '', 'wall_thickness_mm': 39.67},
                {'label': '120', 'wall_thickness_mm': 46.02},
                {'label': '140', 'wall_thickness_mm': 52.37},
                {'label': '160', 'wall_thickness_mm': 59.54}]},
 {'nps': '26',
  'dn': '650',
  'outside_diameter_mm': 660.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4}]},
 {'nps': '28',
  'dn': '700',
  'outside_diameter_mm': 711.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '30', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4}]},
 {'nps': '30',
  'dn': '750',
  'outside_diameter_mm': 762.0,
  'schedules': [{'label': '5', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '30', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '32',
  'dn': '800',
  'outside_diameter_mm': 813.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '30', 'wall_thickness_mm': 15.88},
                {'label': '40', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '34',
  'dn': '850',
  'outside_diameter_mm': 864.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '30', 'wall_thickness_mm': 15.88},
                {'label': '40', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '36',
  'dn': '900',
  'outside_diameter_mm': 914.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 6.35},
                {'label': '', 'wall_thickness_mm': 7.14},
                {'label': '10', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '20 / XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '30', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '40', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '38',
  'dn': '950',
  'outside_diameter_mm': 965.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '40',
  'dn': '1000',
  'outside_diameter_mm': 1016.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 7.92},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '42',
  'dn': '1050',
  'outside_diameter_mm': 1067.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '44',
  'dn': '1100',
  'outside_diameter_mm': 1118.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '46',
  'dn': '1150',
  'outside_diameter_mm': 1168.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '48',
  'dn': '1200',
  'outside_diameter_mm': 1219.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 8.74},
                {'label': 'STD', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': 'XS', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '52',
  'dn': '1300',
  'outside_diameter_mm': 1321.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '56',
  'dn': '1400',
  'outside_diameter_mm': 1422.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '60',
  'dn': '1500',
  'outside_diameter_mm': 1524.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75},
                {'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '64',
  'dn': '1600',
  'outside_diameter_mm': 1626.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 9.53},
                {'label': '', 'wall_thickness_mm': 10.31},
                {'label': '', 'wall_thickness_mm': 11.13},
                {'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '68',
  'dn': '1700',
  'outside_diameter_mm': 1727.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 11.91},
                {'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '72',
  'dn': '1800',
  'outside_diameter_mm': 1829.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '76',
  'dn': '1900',
  'outside_diameter_mm': 1930.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 12.7},
                {'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]},
 {'nps': '80',
  'dn': '2000',
  'outside_diameter_mm': 2032.0,
  'schedules': [{'label': '', 'wall_thickness_mm': 14.27},
                {'label': '', 'wall_thickness_mm': 15.88},
                {'label': '', 'wall_thickness_mm': 17.48},
                {'label': '', 'wall_thickness_mm': 19.05},
                {'label': '', 'wall_thickness_mm': 20.62},
                {'label': '', 'wall_thickness_mm': 22.23},
                {'label': '', 'wall_thickness_mm': 23.83},
                {'label': '', 'wall_thickness_mm': 25.4},
                {'label': '', 'wall_thickness_mm': 26.97},
                {'label': '', 'wall_thickness_mm': 28.58},
                {'label': '', 'wall_thickness_mm': 30.18},
                {'label': '', 'wall_thickness_mm': 31.75}]}]


def _format_schedule_option(schedule: dict) -> str:
    label = str(schedule['label']).strip()
    wall = float(schedule['wall_thickness_mm'])
    if label:
        return f"Sch {label} - {wall:.2f} mm"
    return f"WT {wall:.2f} mm (B36.10)"


def get_pipe_size_options() -> list[str]:
    return [f"NPS {item['nps']} (DN {item['dn']}) - OD {item['outside_diameter_mm']:.2f} mm" for item in PIPE_CATALOG]


def find_pipe_size(option_label: str) -> dict | None:
    for item in PIPE_CATALOG:
        label = f"NPS {item['nps']} (DN {item['dn']}) - OD {item['outside_diameter_mm']:.2f} mm"
        if label == option_label:
            return item
    return None


def get_schedule_options(option_label: str) -> list[str]:
    item = find_pipe_size(option_label)
    if item is None:
        return []
    return [_format_schedule_option(schedule) for schedule in item['schedules']]


def find_schedule(option_label: str, schedule_label: str) -> dict | None:
    item = find_pipe_size(option_label)
    if item is None:
        return None
    for schedule in item['schedules']:
        if _format_schedule_option(schedule) == schedule_label:
            return schedule
    return None
